### ISSUE TITLE
add to maven

### ISSUE THREAD

**Issue by armin-bauer** [Edgewonk/fxcomponents#5]
we want to use this as a maven component in the edgewonk build, so please find out if we can make an artifact from it and upload it to maven. thx

**Comment by malafeev** [comment]
Create request for open source project https://issues.sonatype.org/browse/OSSRH-23553

According to http://central.sonatype.org/pages/ossrh-guide.html

**Comment by malafeev** [comment]
Added.

http://repo1.maven.org/maven2/com/edgewonk/fxcomponents/1.0/
