### ISSUE TITLE
New Component: TextField File Input

### ISSUE THREAD

**Issue by armin-bauer** [Edgewonk/fxcomponents#8]
It would be nice to have a text input field with a button for file selection / input. Core features:

* [x] file is supplied as StringProperty
* [x] filepath is shown in text field
* [x] Button to select a file (normal javafx file open view)
* [x] valid property to see if the file exists

**Comment by armin-bauer** [comment]
@malafeev i think this works, how can i upload it?

**Comment by malafeev** [comment]
I released it. 
Should be available in maven central in a couple of hours.
